### ISSUE TITLE
Negative start

### ISSUE THREAD

**Issue by luc4leone** [arosenfeld2003/testingJavascriptArrayMethods#4]
I think your implementation does not take into account that if negative, the `start` parameter will be counted from the end.

Compare and constrast the result you get from your implementation:

```javascript
[1, 2, 3, 4, 5].myCopyWithin(2, -2, 5);
```

with the native one:

```javascript
[1, 2, 3, 4, 5].copyWithin(2, -2, 5);
```

**Comment by arosenfeld2003** [comment]
Yup - you are correct.  I did not account for this edge case originally.
Refactored.  Thanks for the feedback.
