### ISSUE TITLE
Negative end

### ISSUE THREAD

**Issue by luc4leone** [arosenfeld2003/testingJavascriptArrayMethods#5]
I think your implementation does not take into account that if negative, the `end` parameter will be counted from the end.

Compare and constrast the result you get from your implementation:

```javascript
[1, 2, 3, 4, 5].myCopyWithin(2, 1, -2);
```

with the native one:

```javascript
[1, 2, 3, 4, 5].copyWithin(2, 1, -2);
```

**Comment by arosenfeld2003** [comment]
Again, nice catch on another missed edge case.  Refactored my code.
